import { ChapterInfo } from './types';

export const CHAPTERS: ChapterInfo[] = [
  {
    id: '1',
    slug: 'definizioni-generali-doveri-strada',
    name: 'Definizioni Generali e Doveri',
    description: 'Definizioni, concetti base e doveri del conducente sulla strada',
    icon: 'BookOpen',
    questionCount: 531,
  },
  {
    id: '2',
    slug: 'segnali-pericolo',
    name: 'Segnali di Pericolo',
    description: 'Segnaletica verticale di pericolo: triangoli e signalazioni di rischio',
    icon: 'AlertTriangle',
    questionCount: 662,
  },
  {
    id: '3',
    slug: 'segnali-divieto',
    name: 'Segnali di Divieto',
    description: 'Segnali che indicano divieti e restrizioni sulla circolazione',
    icon: 'Ban',
    questionCount: 521,
  },
  {
    id: '4',
    slug: 'segnali-obbligo',
    name: 'Segnali di Obbligo',
    description: 'Segnali circolari blu che indicano obblighi per i conducenti',
    icon: 'ShieldCheck',
    questionCount: 433,
  },
  {
    id: '5',
    slug: 'segnali-precedenza',
    name: 'Segnali di Precedenza',
    description: 'Regole e segnali relativi alla precedenza tra veicoli',
    icon: 'ArrowRightLeft',
    questionCount: 243,
  },
  {
    id: '6',
    slug: 'segnaletica-orizzontale-ostacoli',
    name: 'Segnaletica Orizzontale',
    description: 'Strisce, frecce e segni sulla carreggiata',
    icon: 'Minus',
    questionCount: 260,
  },
  {
    id: '7',
    slug: 'semafori-vigili',
    name: 'Semafori e Vigili',
    description: 'Regolamentazione semaforica e segnali dei vigili urbani',
    icon: 'TrafficCone',
    questionCount: 253,
  },
  {
    id: '8',
    slug: 'segnali-indicazione',
    name: 'Segnali di Indicazione',
    description: 'Segnali direzionali e di informazione per la guida',
    icon: 'MapPin',
    questionCount: 603,
  },
  {
    id: '9',
    slug: 'segnali-complementari-cantiere',
    name: 'Segnali Complementari',
    description: 'Segnali di cantiere e segnalazioni complementari',
    icon: 'Construction',
    questionCount: 181,
  },
  {
    id: '10',
    slug: 'pannelli-integrativi',
    name: 'Pannelli Integrativi',
    description: 'Pannelli che completano o modificano il significato degli altri segnali',
    icon: 'LayoutGrid',
    questionCount: 263,
  },
  {
    id: '11',
    slug: 'limiti-di-velocita',
    name: 'Limiti di Velocita',
    description: 'Velocita massime e minime consentite per tipo di strada',
    icon: 'Gauge',
    questionCount: 256,
  },
  {
    id: '12',
    slug: 'distanza-di-sicurezza',
    name: 'Distanza di Sicurezza',
    description: 'Distanze di sicurezza tra veicoli e dalla carreggiata',
    icon: 'MoveHorizontal',
    questionCount: 135,
  },
  {
    id: '13',
    slug: 'norme-di-circolazione',
    name: 'Norme di Circolazione',
    description: 'Regole generali per la circolazione stradale',
    icon: 'Route',
    questionCount: 379,
  },
  {
    id: '14',
    slug: 'precedenza-incroci',
    name: 'Precedenza e Incroci',
    description: 'Regole di precedenza agli incroci e nelle intersezioni',
    icon: 'GitBranch',
    questionCount: 415,
  },
  {
    id: '15',
    slug: 'sorpasso',
    name: 'Sorpasso',
    description: 'Regole e modalità per effettuare il sorpasso in sicurezza',
    icon: 'ArrowRight',
    questionCount: 156,
  },
  {
    id: '16',
    slug: 'fermata-sosta-arresto',
    name: 'Fermata e Sosta',
    description: 'Regole per la fermata e la sosta dei veicoli',
    icon: 'ParkingCircle',
    questionCount: 191,
  },
  {
    id: '17',
    slug: 'norme-varie-autostrade-pannelli',
    name: 'Autostrade',
    description: 'Norme specifiche per la circolazione in autostrada',
    icon: 'Road',
    questionCount: 332,
  },
  {
    id: '18',
    slug: 'luci-dispositivi-acustici',
    name: 'Luci e Dispositivi',
    description: 'Luci, frecce e dispositivi acustici del veicolo',
    icon: 'Lightbulb',
    questionCount: 176,
  },
  {
    id: '19',
    slug: 'cinture-casco-sicurezza',
    name: 'Cinture e Casco',
    description: 'Dispositivi di sicurezza: cinture, caschi e seggiolini',
    icon: 'HardHat',
    questionCount: 135,
  },
  {
    id: '20',
    slug: 'patente-punti-documenti',
    name: 'Patente e Punti',
    description: 'Patente di guida, sistema a punti e documenti obbligatori',
    icon: 'CreditCard',
    questionCount: 234,
  },
  {
    id: '21',
    slug: 'incidenti-stradali-comportamenti',
    name: 'Incidenti Stradali',
    description: 'Comportamenti in caso di incidente e prevenzione',
    icon: 'AlertCircle',
    questionCount: 102,
  },
  {
    id: '22',
    slug: 'alcool-droga-primo-soccorso',
    name: 'Alcool, Droga e Soccorso',
    description: 'Limiti alcol, sostanze stupefacenti e primo soccorso',
    icon: 'Heart',
    questionCount: 141,
  },
  {
    id: '23',
    slug: 'responsabilita-civile-penale-e-assicurazione',
    name: 'Responsabilita e Assicurazione',
    description: 'Responsabilita civile, penale e obblighi assicurativi',
    icon: 'Scale',
    questionCount: 149,
  },
  {
    id: '24',
    slug: 'consumi-ambiente-inquinamento',
    name: 'Ambiente e Inquinamento',
    description: 'Consumi, inquinamento e protezione ambientale',
    icon: 'Leaf',
    questionCount: 103,
  },
  {
    id: '25',
    slug: 'elementi-veicolo-manutenzione-comportamenti',
    name: 'Manutenzione Veicolo',
    description: 'Elementi del veicolo, manutenzione e comportamenti di guida',
    icon: 'Wrench',
    questionCount: 285,
  },
];
